# Generated by Django 4.2.7 on 2023-11-20 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(blank=True, max_length=100, verbose_name='address_1')),
                ('address_2', models.CharField(blank=True, max_length=100, verbose_name='address_2')),
                ('profile_picture', models.ImageField(upload_to='userprofile', verbose_name='profile picture')),
                ('city', models.CharField(blank=True, max_length=25, verbose_name='city')),
                ('zip_code', models.CharField(max_length=10, verbose_name='zip code')),
                ('country', models.CharField(max_length=25, verbose_name='country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'userProfile',
                'verbose_name_plural': 'userProfiles',
            },
        ),
    ]
