# Generated by Django 4.2.7 on 2023-11-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='category name')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories', verbose_name='category image')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
