# Generated by Django 4.2.7 on 2023-11-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_order_payment_orderproduct_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'New'), (1, 'Accepted'), (2, 'Completed'), (3, 'Cancelled')], default=0, verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
