# Generated by Django 4.2.7 on 2023-11-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_description_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True, verbose_name='product name')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('price', models.IntegerField(verbose_name='price')),
                ('image', models.ImageField(upload_to='photos/products', verbose_name='image')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
